import {rpc,login,logout,signedIn,uploadImage,imageUrl,deleteImageObject} from './api.js';
import {money,ptaLabel,productKey,escapeHtml as e} from './store.js';
const root=document.querySelector('#portal');
let state={products:[],orders:[],managers:[],owner:false},section='inventory',editKey=null,search='',visibility='',busy=false;
const drafts=new Map();
function shell(content,logged=false){return `<header class="header portal-header"><div class="wrap header-inner"><a class="brand" href="index.html"><img src="applespace-logo.png" alt=""><span>Apple Space</span></a><nav><a href="index.html" target="_blank" rel="noopener">View website ↗</a>${logged?'<button class="btn small" id="logout">Sign out</button>':''}</nav></div></header>${content}`;}
function alertMessage(message,error=false){const n=document.createElement('div');n.className='toast';n.setAttribute('role',error?'alert':'status');n.textContent=message;document.querySelector('.toast')?.remove();document.body.append(n);setTimeout(()=>n.remove(),6000);}
function loginPage(message=''){root.innerHTML=shell(`<main class="panel login"><span class="eyebrow">Website management</span><h1>Welcome back.</h1><p>Sign in to manage product listings, photos, and online order requests.</p><form id="login" class="fields"><label>Email<input type="email" name="email" autocomplete="username" required></label><label>Password<input type="password" name="password" autocomplete="current-password" required></label><div class="error" id="login-error" role="alert">${e(message)}</div><button class="btn" type="submit">Sign in →</button></form><p class="checkout-note">Access is assigned by the owner. Use your website-management account.</p></main>`);}
function stats(){return `<div class="stats"><div class="stat"><span>Available products</span><strong>${state.products.filter(p=>p.quantity>0).length}</strong></div><div class="stat"><span>Published & available</span><strong>${state.products.filter(p=>p.published&&p.quantity>0).length}</strong></div><div class="stat"><span>Pending order requests</span><strong>${state.orders.filter(o=>o.status==='pending').length}</strong></div></div>`;}
function inventory(){return `<h1>Website inventory</h1><p style="font-size:12px">Select products from shop stock, add photos, and choose what appears online.</p>${stats()}<div class="filters"><input id="search" type="search" placeholder="Search model, colour or stock code" aria-label="Search website inventory" value="${e(search)}"><select id="visibility" aria-label="Filter visibility"><option value="">All products</option><option value="published">Published</option><option value="hidden">Hidden</option></select><button class="btn alt small" id="refresh">Refresh stock ↻</button></div><div class="table-wrap"><table><thead><tr><th>Product</th><th>Type</th><th>Selling price</th><th>Stock</th><th>Website</th><th>Photos</th><th></th></tr></thead><tbody id="inventory-rows"></tbody></table></div>`;}
function rows(){const filtered=state.products.filter(p=>[p.title,p.model,p.color,p.stock_code].join(' ').toLowerCase().includes(search.toLowerCase())&&(!visibility||(visibility==='published'?p.published:!p.published)));document.querySelector('#inventory-rows').innerHTML=filtered.map(p=>`<tr><td><strong>${e(p.title)}</strong><br><span class="muted">${e([p.stock_code,p.storage,ptaLabel(p.pta_status)].filter(Boolean).join(' · '))}</span></td><td>${p.kind==='iphone'?'iPhone':'Accessory'}</td><td>${p.price>0?money(p.price):'Not set'}</td><td>${e(p.status.replaceAll('_',' '))}${p.kind==='accessory'?' · '+p.quantity:''}</td><td><span class="status ${!p.published||!p.quantity?'hidden':''}">${p.published&&p.quantity?'Published':'Hidden'}</span></td><td>${p.images.length}/8</td><td><button class="btn alt small" data-edit="${productKey(p)}">Manage →</button></td></tr>`).join('')||'<tr><td colspan="7">No matching inventory. Products purchased in the ERP will appear here.</td></tr>';}
function editor(){const p=state.products.find(p=>productKey(p)===editKey);if(!p){editKey=null;return inventory();}const d=drafts.get(editKey)||p;return `<button class="btn alt small" id="back">← Inventory</button><h1 style="margin-top:28px">${e(p.model)}</h1><p style="font-size:12px">${e([p.stock_code,p.storage,p.color,ptaLabel(p.pta_status)].filter(Boolean).join(' · '))}</p><div class="editor"><section class="panel"><h2 style="font-size:23px">Listing details</h2><form class="fields" id="listing"><label>Website title<input name="title" maxlength="160" required value="${e(d.title)}"></label><label>Website selling price (Rs)<input name="price" type="number" min="1" step="0.01" required value="${e(d.price||'')}"></label><label>Product description<textarea name="description" maxlength="5000">${e(d.description)}</textarea></label><label class="checkbox"><input name="published" type="checkbox" ${d.published?'checked':''} ${p.quantity<1?'disabled':''}>Display this product on the website</label>${p.quantity<1?'<div class="notice">This product is unavailable. It cannot be published until it returns to available stock.</div>':''}<div class="error" id="listing-error" role="alert"></div><button type="submit" class="btn">Save listing</button><a class="text-link" href="product.html?kind=${p.kind}&id=${p.id}" target="_blank" rel="noopener">View public product page ↗</a></form></section><section class="panel"><h2 style="font-size:23px">Product photos</h2><p style="font-size:12px">Upload up to 8 JPG, PNG or WebP images. Maximum 5 MB each. The cover photo appears first.</p><label>Add photos<input type="file" id="photos" accept="image/jpeg,image/png,image/webp" multiple ${p.images.length>=8?'disabled':''}></label><div class="media-grid">${p.images.map((m,i)=>`<div><img src="${e(imageUrl(m.path))}" alt="${e(m.alt||p.title)}"><div class="row"><button data-cover="${m.id}" ${i===0?'disabled':''}>${i===0?'Cover':'Make cover'}</button><button data-delete="${m.id}">Remove</button></div></div>`).join('')}</div><p id="upload-status" class="muted" role="status" style="font-size:12px"></p></section></div>`;}
function orders(){return `<h1>Online order requests</h1><p style="font-size:12px">Confirm availability and payment with the customer. Record the completed sale in the ERP to update shop stock.</p><div class="notice">Changing an order status here does not sell or reserve stock. The inventory system remains the source of stock availability.</div><button class="btn alt small" id="refresh" style="margin-bottom:20px">Refresh orders ↻</button>${state.orders.map(o=>`<article class="order-card"><div class="row" style="justify-content:space-between"><h3>#${e(o.id.slice(0,8).toUpperCase())} · ${e(o.customer_name)}</h3><span class="status ${o.status==='cancelled'?'hidden':''}">${e(o.status)}</span></div><p>${e(o.phone)} · ${e(new Date(o.created_at).toLocaleString())}<br>${o.fulfilment==='delivery'?'Delivery request':'Shop pickup'}${o.address?'<br>'+e(o.address):''}</p><div class="order-items">${o.items.map(i=>`${e(i.quantity)} × ${e(i.title)} — ${money(i.price*i.quantity)}`).join('<br>')}</div><div class="total-line"><span>Products total</span><span>${money(o.total)}</span></div>${o.notes?'<p>Notes: '+e(o.notes)+'</p>':''}<div class="row" style="margin-top:18px"><label>Order status<select data-order="${o.id}" aria-label="Status for order ${e(o.id.slice(0,8))}">${['pending','confirmed','completed','cancelled'].map(s=>`<option value="${s}" ${s===o.status?'selected':''}>${s[0].toUpperCase()+s.slice(1)}</option>`).join('')}</select></label><a class="btn alt small" href="https://wa.me/${e(o.phone.replace(/\D/g,'').replace(/^0/,'92'))}?text=${encodeURIComponent('Hi '+o.customer_name+', this is Apple Space regarding your order '+o.id.slice(0,8).toUpperCase()+'.')}" target="_blank" rel="noopener">Contact customer ↗</a></div></article>`).join('')||'<div class="empty"><h3>No order requests yet.</h3><p>Orders submitted on the website will appear here.</p></div>'}`;}
function managers(){return `<h1>Website team</h1><p style="font-size:12px">Give a separate website-only account access to listings and orders. ERP staff accounts cannot be added here.</p><section class="panel" style="max-width:650px"><h2 style="font-size:23px">Grant website access</h2><p style="font-size:12px">First create the user in Supabase Authentication with email confirmation, then enter their email here. Do not assign them an ERP staff role.</p><form id="manager" class="fields"><label>Account email<input name="email" type="email" required></label><div id="manager-error" class="error" role="alert"></div><button class="btn" type="submit">Grant website access</button></form></section><div class="table-wrap" style="margin-top:28px"><table><thead><tr><th>Email</th><th>Access</th><th></th></tr></thead><tbody>${state.managers.map(m=>`<tr><td>${e(m.email)}</td><td>${m.active?'Active':'Disabled'}</td><td><button class="btn alt small" data-manager-email="${e(m.email)}" data-active="${!m.active}">${m.active?'Disable access':'Enable access'}</button></td></tr>`).join('')||'<tr><td colspan="3">No website managers added yet.</td></tr>'}</tbody></table></div>`;}
function render(){root.innerHTML=shell(`<div class="portal-layout"><aside class="sidebar" aria-label="Portal navigation">${[['inventory','Product listings'],['orders','Order requests'],...(state.owner?[['managers','Website team']]:[])].map(([s,t])=>`<button data-section="${s}" class="${s===section?'active':''}" ${s===section?'aria-current="page"':''}>${t}</button>`).join('')}</aside><main class="portal-main">${section==='inventory'?(editKey?editor():inventory()):section==='orders'?orders():managers()}</main></div>`,true);if(section==='inventory'&&!editKey){document.querySelector('#visibility').value=visibility;rows();}}
async function load(){state=await rpc('store_portal',{},true);if(editKey&&!state.products.some(p=>productKey(p)===editKey)){drafts.delete(editKey);editKey=null;alertMessage('The product is no longer available.');}render();}
function capture(){if(!editKey)return;const f=document.querySelector('#listing');if(!f)return;const d=Object.fromEntries(new FormData(f));drafts.set(editKey,{title:d.title,price:d.price,description:d.description,published:f.elements.published.checked});}
async function action(p){if(busy)return;busy=true;try{await rpc('store_update',{p},true);await load();alertMessage('Saved.');}catch(error){alertMessage(error.message,true);}finally{busy=false;}}
root.addEventListener('input',ev=>{if(ev.target.id==='search'){search=ev.target.value;rows();}if(ev.target.closest('#listing'))capture();});
root.addEventListener('click',async ev=>{
 const sectionBtn=ev.target.closest('[data-section]');if(sectionBtn){capture();section=sectionBtn.dataset.section;editKey=null;render();}
 const edit=ev.target.closest('[data-edit]');if(edit){editKey=edit.dataset.edit;render();}
 if(ev.target.closest('#back')){capture();editKey=null;render();}
 if(ev.target.closest('#logout')){await logout();state={products:[],orders:[],managers:[],owner:false};drafts.clear();loginPage();}
 if(ev.target.closest('#refresh')){try{await load();alertMessage('Stock refreshed.');}catch(error){alertMessage(error.message,true);}}
 const cover=ev.target.closest('[data-cover]');if(cover){capture();await action({action:'media_cover',media_id:cover.dataset.cover});}
 const remove=ev.target.closest('[data-delete]');if(remove){capture();const p=state.products.find(p=>productKey(p)===editKey),m=p.images.find(m=>m.id===remove.dataset.delete);await action({action:'media_remove',media_id:m.id}); // Detach first; deletion may be disallowed for another user's upload.
 if(!state.products.find(p=>productKey(p)===editKey)?.images.some(x=>x.id===m.id)) await deleteImageObject(m.path).catch(()=>{});}
 const manager=ev.target.closest('[data-manager-email]');if(manager)await action({action:'manager',email:manager.dataset.managerEmail,active:manager.dataset.active==='true'});
});
root.addEventListener('change',async ev=>{
 if(ev.target.id==='visibility'){visibility=ev.target.value;rows();}
 if(ev.target.closest('#listing'))capture();
 if(ev.target.dataset.order)await action({action:'order_status',id:ev.target.dataset.order,status:ev.target.value});
 if(ev.target.id==='photos'){
  capture();if(busy)return;const p=state.products.find(p=>productKey(p)===editKey),files=[...ev.target.files];if(files.length+p.images.length>8)return alertMessage('Maximum eight photos per product.',true);
  busy=true;let done=0;ev.target.disabled=true;
  try{for(const file of files){document.querySelector('#upload-status').textContent=`Uploading photo ${done+1} of ${files.length}…`;await uploadImage(file,{...p,images:[...p.images,...Array(done).fill({})]});done++;}alertMessage('Photos uploaded.');}
  catch(error){alertMessage(error.message,true);}finally{busy=false;await load().catch(error=>alertMessage(error.message,true));}
 }
});
root.addEventListener('submit',async ev=>{
 ev.preventDefault();const f=ev.target,btn=f.querySelector('button[type="submit"]');if(busy)return;busy=true;btn.disabled=true;
 try{
  if(f.id==='login'){const d=Object.fromEntries(new FormData(f));await login(d.email,d.password);try{await load();}catch(error){await logout();throw error;}}
  if(f.id==='listing'){capture();const p=state.products.find(p=>productKey(p)===editKey);await rpc('store_update',{p:{action:'listing',id:p.id,kind:p.kind,...drafts.get(editKey)}},true);drafts.delete(editKey);await load();alertMessage('Listing saved.');}
  if(f.id==='manager'){await rpc('store_update',{p:{action:'manager',email:f.elements.email.value,active:true}},true);await load();alertMessage('Website access granted.');}
 }catch(error){const n=f.querySelector('.error');if(n)n.textContent=error.message;else alertMessage(error.message,true);}
 finally{busy=false;btn.disabled=false;}
});
if(signedIn()){root.innerHTML=shell('<main class="loading">Loading your website portal…</main>');try{await load();}catch(error){await logout();loginPage(error.message);}}else loginPage();
