import {rpc,imageUrl} from './api.js';
import {config} from './config.js';
import {money,ptaLabel,productKey,reconcileCart,cartLines,cartTotal,escapeHtml as e} from './store.js';
const root=document.querySelector('#app');
const page=document.body.dataset.page||'home';
let products=[],cart=[],filters={search:'',pta:'',sort:'newest'},timer,requestId=crypto.randomUUID(),submitting=false;
try{const saved=JSON.parse(localStorage.getItem('applespace-cart')||'[]');cart=Array.isArray(saved)?saved.filter(l=>typeof l.key==='string'&&Number.isFinite(l.quantity)).slice(0,20):[];}catch{}
const icon='<svg viewBox="0 0 60 80" fill="none" aria-hidden="true"><rect x="8" y="2" width="44" height="76" rx="9" stroke="currentColor" stroke-width="3"/><path d="M23 9h14M24 71h12" stroke="currentColor" stroke-width="3"/></svg>';
function saveCart(){try{localStorage.setItem('applespace-cart',JSON.stringify(cart));}catch{}requestId=crypto.randomUUID();updateCount();}
function updateCount(){document.querySelectorAll('[data-cart-count]').forEach(n=>n.textContent=cart.reduce((s,l)=>s+l.quantity,0));}
function toast(message){document.querySelector('.toast')?.remove();const t=document.createElement('div');t.className='toast';t.setAttribute('role','status');t.textContent=message;document.body.append(t);clearTimeout(timer);timer=setTimeout(()=>t.remove(),5000);}
function header(){return `<div class="topline">Apple Space · Visit us at Noor Mobile Mall, 6th Road, Rawalpindi</div><header class="header"><div class="wrap header-inner"><a class="brand" href="index.html"><img src="applespace-logo.png" alt=""><span>Apple Space</span></a><nav aria-label="Main navigation">${[['home','Home','index.html'],['iphones','iPhones','iphones.html'],['accessories','Accessories','accessories.html'],['about','About Us','about.html']].map(([id,title,href])=>`<a href="${href}" ${page===id?'class="active" aria-current="page"':''}>${title}</a>`).join('')}</nav><a class="cart-link" href="cart.html" aria-label="View shopping cart">Cart <span class="cart-count" data-cart-count>0</span></a></div></header>`;}
function footer(){return `<footer class="footer"><div class="wrap footer-top"><div><a class="brand" href="index.html"><img src="applespace-logo.png" alt=""><span>Apple Space</span></a><p>Phones, accessories, and a space to check them comfortably before you buy.</p></div><div><h3>Explore</h3><a href="iphones.html">iPhones</a><a href="accessories.html">Accessories</a><a href="about.html">About Us</a><a href="cart.html">Your cart</a></div><div><h3>Visit & connect</h3><a href="${config.maps}" target="_blank" rel="noopener">Find Us ↗</a><a href="https://wa.me/${config.whatsapp}" target="_blank" rel="noopener">WhatsApp ↗</a><a href="https://www.instagram.com/aspace.pk/" target="_blank" rel="noopener">Instagram ↗</a><a class="footer-admin" href="admin.html">Website manager sign in</a></div></div><div class="wrap footer-bottom"><span>© ${new Date().getFullYear()} Apple Space</span><span>Shop 103 & 104 · Noor Mobile Mall · Rawalpindi</span></div></footer>`;}
function photo(p,cls='product-photo'){return `<div class="${cls}">${p.images?.length?`<img src="${e(imageUrl(p.images[0].path))}" alt="${e(p.images[0].alt||p.title)}" loading="lazy">`:`<div class="no-photo">${icon}<span>Photos coming soon</span></div>`}</div>`;}
function card(p){return `<article class="product-card"><a href="product.html?kind=${p.kind}&id=${p.id}" aria-label="View ${e(p.title)}">${photo(p).replace(/<\/div>$/, `<span class="tag">${e(p.kind==='iphone'?ptaLabel(p.pta_status):p.category||'Accessory')}</span></div>`)}<div class="card-body"><h3>${e(p.title)}</h3><p>${e(p.kind==='iphone'?[p.storage,p.color,p.battery_health?`${p.battery_health}% battery`:''].filter(Boolean).join(' · '):p.category||'In stock')}</p></div></a><div class="card-body" style="padding-top:0"><div class="card-bottom"><span class="price">${money(p.price)}</span><button class="add" data-add="${productKey(p)}" aria-label="Add ${e(p.title)} to cart">+</button></div></div></article>`;}
function empty(kind='products'){return `<div class="empty"><h3>${kind==='search'?'No matching products':'New stock is on its way.'}</h3><p>${kind==='search'?'Try another search or clear your filters.':'Check back for available '+e(kind)+', or message us for the latest stock.'}</p><a class="btn alt" href="https://wa.me/${config.whatsapp}" target="_blank" rel="noopener">Ask about availability ↗</a></div>`;}
function home(){const phones=products.filter(p=>p.kind==='iphone').slice(0,4),accessories=products.filter(p=>p.kind==='accessory').slice(0,4);return `<main>
<section class="hero-scene"><div class="wrap hero"><div class="hero-copy"><span class="eyebrow"><i class="live-dot"></i> Apple Space / Rawalpindi</span><h1>A new phone.<br>A whole new<br><em>feeling.</em></h1><p>The upgrade you’ve been thinking about.<br>A space to make it yours.</p><div class="row"><a class="btn" href="iphones.html">Find your iPhone <span>↗</span></a><a class="text-link" href="about.html">Discover our space ↗</a></div><div class="hero-footnote"><span>01 — THE NEXT CHAPTER</span><a href="#collection">Scroll to explore ↓</a></div></div>
<div class="hero-art" aria-label="Animated burgundy phone concept rotating from back to front"><div class="orbit orbit-one"></div><div class="orbit orbit-two"></div><span class="art-word" aria-hidden="true">SPACE</span><div class="phone-stage"><div class="rotating-phone"><div class="phone-face phone-back"><div class="camera"><i></i><i></i><i></i></div><span class="phone-brand">Apple<br>Space</span><span class="phone-edition">THE BURGUNDY CONCEPT</span></div><div class="phone-face phone-front"><div class="screen-wallpaper"></div><div class="dynamic-island"></div><div class="screen-time"><span>Make room for something new.</span><strong>9:41</strong></div><div class="screen-bottom">Your next chapter. <span>↗</span></div></div></div></div><div class="art-label"><span><i class="live-dot"></i> A DIFFERENT PERSPECTIVE</span><button class="motion-toggle" data-motion aria-pressed="false" aria-label="Pause decorative animations">Pause motion Ⅱ</button></div></div></div></section>
<div class="marquee" aria-hidden="true"><div>${Array(4).fill('<span>YOUR NEXT UPGRADE</span><i>✳</i><span>YOUR OWN SPACE</span><i>✳</i>').join('')}</div></div>
<section class="wrap trust"><div><span class="trust-number">01</span><strong>Available. Right now.</strong><span>Connected to our live inventory</span></div><div><span class="trust-number">02</span><strong>Get a closer look.</strong><span>Visit the shop before you decide</span></div><div><span class="trust-number">03</span><strong>Talk to real people.</strong><span>Your questions, answered on WhatsApp</span></div></section>
<section class="wrap section" id="collection"><div class="section-head"><div><span class="eyebrow">The collection / 01</span><h2>Meet your next <em>iPhone.</em></h2><p>Current stock. Every detail, at a glance.</p></div><a class="text-link" href="iphones.html">Explore the collection ↗</a></div><div class="grid">${phones.length?phones.map(card).join(''):empty('iPhones')}</div></section>
<section class="wrap space-section"><div class="feature"><div class="feature-image"><img src="inner-space.jpg" alt="Apple Space inner office with seating for checking phones" loading="lazy"><span class="image-caption">OUR SPACE / RAWALPINDI</span></div><div class="feature-copy"><span class="eyebrow">A little more personal</span><h2>Good phones.<br><em>Great conversations.</em></h2><p>Walk in. Take a seat. Get to know your next phone. Our space is made for questions, closer looks, and decisions that feel right.</p><a class="btn alt" href="about.html">Come inside ↗</a><span class="feature-number" aria-hidden="true">AS.</span></div></div></section>
<section class="wrap section"><div class="section-head"><div><span class="eyebrow">The essentials / 02</span><h2>The little things.<br><em>The big difference.</em></h2><p>Accessories for wherever your day takes you.</p></div><a class="text-link" href="accessories.html">Explore accessories ↗</a></div><div class="grid">${accessories.length?accessories.map(card).join(''):empty('accessories')}</div></section>
<section class="wrap visit-banner"><span class="eyebrow">Online is only the beginning</span><h2>See you at<br><em>Apple Space.</em></h2><div><p>Noor Mobile Mall, 6th Road<br>Rawalpindi, Pakistan</p><a class="btn" href="${config.maps}" target="_blank" rel="noopener">Find our space ↗</a></div></section></main>`;}
function filtered(){let list=products.filter(p=>p.kind===(page==='iphones'?'iphone':'accessory'));const term=filters.search.toLowerCase();list=list.filter(p=>[p.title,p.model,p.storage,p.color,p.category].join(' ').toLowerCase().includes(term)&&(!filters.pta||p.pta_status===filters.pta));if(filters.sort==='low')list.sort((a,b)=>a.price-b.price);if(filters.sort==='high')list.sort((a,b)=>b.price-a.price);return list;}
function catalogue(){return `<main class="wrap"><section class="page-title"><span class="eyebrow">${page==='iphones'?'Your next upgrade':'Made for your everyday'}</span><h1>${page==='iphones'?'Explore iPhones.':'The right accessories.'}</h1><p>Browse what is available now. Order online or talk to us before you decide.</p></section><div class="filters"><input aria-label="Search products" id="search" type="search" placeholder="Search ${page==='iphones'?'model, storage or colour':'accessories'}" value="${e(filters.search)}">${page==='iphones'?`<select id="pta" aria-label="Filter PTA status"><option value="">All PTA statuses</option><option value="pta_approved">PTA Approved</option><option value="non_pta">Non-PTA</option><option value="jv">JV</option></select>`:''}<select id="sort" aria-label="Sort products"><option value="newest">Newest arrivals</option><option value="low">Price: low to high</option><option value="high">Price: high to low</option></select></div><div class="muted" id="result-count" style="font-size:11px;margin-bottom:18px"></div><div class="grid" id="product-grid"></div><div style="height:55px"></div></main>`;}
function updateCatalogue(){const list=filtered();document.querySelector('#product-grid').innerHTML=list.length?list.map(card).join(''):empty(filters.search||filters.pta?'search':page);document.querySelector('#result-count').textContent=`${list.length} product${list.length===1?'':'s'} available`;animatePage();}
function detail(){const query=new URLSearchParams(location.search),p=products.find(p=>p.id===query.get('id')&&p.kind===query.get('kind'));if(!p)return `<main class="wrap section"><div class="empty"><h1 style="font-size:32px">This product is unavailable.</h1><p>It may have sold or been removed from the website.</p><a class="btn" href="iphones.html">Browse available stock</a></div></main>`;const specs=p.kind==='iphone'?[['Storage',p.storage],['Colour',p.color],['PTA status',ptaLabel(p.pta_status)],['Battery health',p.battery_health?`${p.battery_health}%`:'Ask us'],['Condition',p.condition||'Ask us'],['Availability','In stock']]:[['Category',p.category||'Accessory'],['Availability',`${p.quantity} in stock`]];return `<main class="wrap section"><a class="text-link" href="${p.kind==='iphone'?'iphones':'accessories'}.html">← Back to ${p.kind==='iphone'?'iPhones':'accessories'}</a><section class="detail"><div>${photo(p,'detail-photo')}<div class="thumbs">${(p.images||[]).map((m,i)=>`<button data-photo="${e(imageUrl(m.path))}" aria-label="View photo ${i+1}"><img src="${e(imageUrl(m.path))}" alt="${e(m.alt||p.title)}"></button>`).join('')}</div></div><div><span class="eyebrow">${p.kind==='iphone'?'Available iPhone':'Available accessory'}</span><h1>${e(p.title)}</h1><div class="price" style="font-size:28px">${money(p.price)}</div><div class="specs">${specs.map(([k,v])=>`<div><span>${e(k)}</span>${e(v||'Ask us')}</div>`).join('')}</div><p style="font-size:13px;white-space:pre-line">${e(p.description||'For more details about this product, contact our team or visit the shop.')}</p><div class="row"><button class="btn" data-add="${productKey(p)}">Add to cart +</button><a class="btn alt" href="https://wa.me/${config.whatsapp}?text=${encodeURIComponent('Hi Apple Space, I would like to know more about '+p.title+' ('+money(p.price)+').')}" target="_blank" rel="noopener">Ask on WhatsApp ↗</a></div><p class="checkout-note">Availability is checked again when you submit your order request.</p></div></section></main>`;}
function about(){return `<main class="wrap section"><div class="page-title" style="padding-top:0"><span class="eyebrow">Get to know us</span><h1>Your next iPhone.<br>Your own space.</h1><p style="max-width:630px">Welcome to Apple Space — a place to explore iPhones and accessories, ask questions, and check your next phone comfortably before you buy.</p></div><div class="about-photos"><figure><a href="shop-exterior.jpg" target="_blank" rel="noopener"><img src="shop-exterior.jpg" alt="Apple Space shop front with iPhones on display" width="1350" height="1800"></a><figcaption><span class="eyebrow">01 / Our shop</span><h2>Step into Apple Space.</h2><p>Visit our shop and explore the phones and accessories in person.</p></figcaption></figure><figure><a href="inner-space.jpg" target="_blank" rel="noopener"><img src="inner-space.jpg" alt="Apple Space inner office with sofas and a desk" width="1800" height="1350" loading="lazy"></a><figcaption><span class="eyebrow">02 / The inner space</span><h2>Take a seat. Take your time.</h2><p>A comfortable space to sit, talk, and check your phone before making a decision.</p></figcaption></figure></div><section class="contact-card"><div><span class="eyebrow">Come and see us</span><h2>Find your way to Apple Space.</h2><p>Shop no. 103 & 104, Mezzanine Floor,<br>Noor Mobile Mall, 6th Road, Rawalpindi<br><a href="https://wa.me/${config.whatsapp}">+92 334 5136382</a></p></div><div class="row"><a class="btn" href="${config.maps}" target="_blank" rel="noopener">Find Us ↗</a><a class="btn alt" href="https://wa.me/${config.whatsapp}" target="_blank" rel="noopener">WhatsApp ↗</a></div></section></main>`;}
function cartPage(){const lines=cartLines(cart,products);return `<main class="wrap section"><div class="page-title" style="padding-top:0"><span class="eyebrow">Your selection</span><h1>Your cart.</h1><p>Choose pickup or request delivery. Our team will confirm your order.</p></div>${!lines.length?`<div class="empty"><h3>Your cart is empty.</h3><p>Explore our available products to find your next upgrade.</p><a class="btn" href="iphones.html">Explore iPhones ↗</a></div>`:`<div class="checkout-grid"><div>${lines.map(p=>`<article class="cart-row">${p.images?.length?`<img src="${e(imageUrl(p.images[0].path))}" alt="${e(p.title)}">`:''}<div class="cart-info"><h3><a href="product.html?kind=${p.kind}&id=${p.id}">${e(p.title)}</a></h3><p>${e([p.storage,p.color,ptaLabel(p.pta_status)].filter(Boolean).join(' · '))}</p><div class="qty"><button data-qty="${productKey(p)}" data-change="-1" aria-label="Decrease quantity">−</button><span>${p.quantity}</span><button data-qty="${productKey(p)}" data-change="1" ${p.quantity>=p.maxQuantity?'disabled':''} aria-label="Increase quantity">+</button><button class="remove" data-remove="${productKey(p)}">Remove</button></div></div><strong>${money(p.price*p.quantity)}</strong></article>`).join('')}<p class="checkout-note">Cart prices and availability follow current stock. A cart does not reserve a phone.</p><button class="btn alt small" id="refresh-cart">Refresh prices & stock ↻</button></div><section class="panel"><h2 style="font-size:25px">Order summary</h2><div class="total-line"><span>Products total</span><span>${money(cartTotal(lines))}</span></div><p class="checkout-note">Delivery charges, if applicable, will be confirmed by the shop. No online payment is collected here.</p><form id="checkout" class="fields"><label>Full name<input name="name" required minlength="2" maxlength="100" autocomplete="name"></label><label>Phone / WhatsApp<input name="phone" type="tel" required pattern="[+0-9 ()-]{10,20}" maxlength="20" autocomplete="tel" placeholder="03xx xxxxxxx"></label><label>Receive your order<select name="fulfilment" id="fulfilment"><option value="pickup">Pick up at the shop</option><option value="delivery">Request delivery</option></select></label><label id="address-label" hidden>Complete delivery address<textarea name="address" maxlength="600" autocomplete="street-address"></textarea></label><label>Notes (optional)<textarea name="notes" maxlength="1000" style="min-height:70px" placeholder="Anything you would like us to know?"></textarea></label><label class="honeypot" aria-hidden="true">Company<input name="company" tabindex="-1" autocomplete="off"></label><div id="checkout-error" class="error" role="alert"></div><button class="btn" type="submit">Submit order request ↗</button><p class="checkout-note" style="margin:0">Your order becomes final after our team confirms stock and payment details.</p></form></section></div>`}</main>`;}
let revealObserver;
function animatePage(){
 const motion=root.querySelector('[data-motion]');if(motion&&document.body.classList.contains('motion-paused')){motion.setAttribute('aria-pressed','true');motion.setAttribute('aria-label','Play decorative animations');motion.textContent='Play motion ▷';}
 revealObserver?.disconnect();
 if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;
 revealObserver=new IntersectionObserver(entries=>{for(const entry of entries){if(entry.isIntersecting){entry.target.classList.add('in-view');revealObserver.unobserve(entry.target);}}},{threshold:.08});
 root.querySelectorAll('.section-head,.product-card,.feature,.trust>div,.about-photos figure,.contact-card,.visit-banner,.page-title,.empty').forEach((el,i)=>{if(!el.classList.contains('reveal')){el.classList.add('reveal');el.style.setProperty('--delay',`${Math.min(i%4,3)*70}ms`);}revealObserver.observe(el);});
}
function render(){root.innerHTML=header()+({home,iphones:catalogue,accessories:catalogue,product:detail,about,cart:cartPage}[page]||home)()+footer();updateCount();if(page==='iphones'||page==='accessories'){document.querySelector('#pta')?.setAttribute('value',filters.pta);if(document.querySelector('#pta'))document.querySelector('#pta').value=filters.pta;document.querySelector('#sort').value=filters.sort;updateCatalogue();}animatePage();}
async function refresh(){const fresh=await rpc('store_catalog');if(!Array.isArray(fresh))throw new Error('Unable to load products.');products=fresh;const next=reconcileCart(cart,products);const changed=JSON.stringify(next)!==JSON.stringify(cart);cart=next;if(changed){saveCart();toast('Your cart was updated to match current availability.');}return changed;}
root.addEventListener('input',ev=>{if(ev.target.id==='search'){filters.search=ev.target.value;updateCatalogue();}});
root.addEventListener('change',ev=>{if(['pta','sort'].includes(ev.target.id)){filters[ev.target.id]=ev.target.value;updateCatalogue();}if(ev.target.id==='fulfilment'){const delivery=ev.target.value==='delivery';document.querySelector('#address-label').hidden=!delivery;document.querySelector('[name="address"]').required=delivery;}});
root.addEventListener('click',ev=>{
 const motion=ev.target.closest('[data-motion]');if(motion){const paused=document.body.classList.toggle('motion-paused');motion.setAttribute('aria-pressed',String(paused));motion.setAttribute('aria-label',paused?'Play decorative animations':'Pause decorative animations');motion.textContent=paused?'Play motion ▷':'Pause motion Ⅱ';return;}
 if(ev.target.closest('#refresh-cart')){refresh().then(()=>{render();toast('Prices and stock refreshed.');}).catch(error=>toast(error.message));return;}
 const add=ev.target.closest('[data-add]');if(add){const p=products.find(p=>productKey(p)===add.dataset.add);if(!p)return;const line=cart.find(l=>l.key===productKey(p));if(line&&line.quantity>=Math.min(20,p.quantity))return toast('All available units are already in your cart.');if(!line&&cart.length>=20)return toast('You can order up to 20 different products.');if(line)line.quantity++;else cart.push({key:productKey(p),quantity:1});saveCart();toast('Added to your cart.');}
 const qty=ev.target.closest('[data-qty]');if(qty){const line=cart.find(l=>l.key===qty.dataset.qty);if(line){line.quantity+=Number(qty.dataset.change);cart=cart.filter(l=>l.quantity>0);cart=reconcileCart(cart,products);saveCart();render();}}
 const remove=ev.target.closest('[data-remove]');if(remove){cart=cart.filter(l=>l.key!==remove.dataset.remove);saveCart();render();}
 const thumb=ev.target.closest('[data-photo]');if(thumb){const image=document.querySelector('.detail-photo img');if(image)image.src=thumb.dataset.photo;}
});
root.addEventListener('submit',async ev=>{
 if(ev.target.id!=='checkout')return;ev.preventDefault();if(submitting)return;const form=ev.target,data=Object.fromEntries(new FormData(form));if(data.company)return;const lines=cartLines(cart,products),btn=form.querySelector('button[type="submit"]');submitting=true;btn.disabled=true;btn.textContent='Checking availability…';
 try{const result=await rpc('store_checkout',{p:{request_id:requestId,name:data.name,phone:data.phone,fulfilment:data.fulfilment,address:data.address,notes:data.notes,items:lines.map(p=>({id:p.id,kind:p.kind,quantity:p.quantity,price:p.price}))}});cart=[];saveCart();const message='Hi Apple Space, I submitted order '+result.id.slice(0,8).toUpperCase()+' for '+money(result.total)+'. Please confirm my order.';root.innerHTML=header()+`<main class="wrap section"><div class="panel" style="max-width:700px;margin:auto"><span class="eyebrow">Order request received</span><h1 style="font-size:40px">Thank you, ${e(data.name)}.</h1><p>Reference: <strong>${e(result.id.slice(0,8).toUpperCase())}</strong><br>Products total: <strong>${money(result.total)}</strong></p><p>Our team will confirm availability, payment and ${data.fulfilment==='delivery'?'delivery arrangements':'pickup details'}. Your request has been saved.</p><div class="row"><a class="btn" href="https://wa.me/${config.whatsapp}?text=${encodeURIComponent(message)}" target="_blank" rel="noopener">Follow up on WhatsApp ↗</a><a class="btn alt" href="iphones.html">Continue shopping</a></div></div></main>`+footer();updateCount();}
 catch(error){form.querySelector('#checkout-error').textContent=error.message;}
 finally{submitting=false;btn.disabled=false;btn.textContent='Submit order request ↗';}
});
root.innerHTML=header()+'<main class="wrap loading" role="status">Loading Apple Space…</main>'+footer();updateCount();
try{await refresh();render();}catch(error){if(page==='about'){render();}else{root.innerHTML=header()+`<main class="wrap section"><div class="panel site-error"><h2>We could not load the shop.</h2><p>${e(error.message)}</p><div class="row"><button class="btn" id="retry">Try again</button><a class="btn alt" href="https://wa.me/${config.whatsapp}" target="_blank" rel="noopener">Contact us</a></div></div></main>`+footer();document.querySelector('#retry').onclick=()=>location.reload();}}
// Re-fetch on return and every 30 seconds. Never cache sold phones indefinitely.
async function backgroundRefresh(){if(document.hidden||submitting||page==='cart')return;try{await refresh();if(page==='iphones'||page==='accessories')updateCatalogue();else if(page==='home'||page==='product')render();}catch{}}
setInterval(backgroundRefresh,30000);window.addEventListener('focus',backgroundRefresh);
