export const databaseUrl='https://ghmofddxpflpopwavysk.supabase.co';
const key='sb_publishable_tR1UVusyf4w2m9JdiHaLvg_zgpIFraR';
export function session(){try{return JSON.parse(sessionStorage.getItem('aspace-session')||'null')}catch{return null}}
export async function signIn(email,password){const r=await fetch(databaseUrl+'/auth/v1/token?grant_type=password',{method:'POST',signal:AbortSignal.timeout(20000),headers:{apikey:key,'Content-Type':'application/json'},body:JSON.stringify({email,password})});const b=await r.json();if(!r.ok)throw Error(b.msg||b.error_description||'Sign in failed');sessionStorage.setItem('aspace-session',JSON.stringify(b));return b}
export async function signOut(){const s=session();sessionStorage.removeItem('aspace-session');if(s)await fetch(databaseUrl+'/auth/v1/logout',{method:'POST',signal:AbortSignal.timeout(20000),headers:{apikey:key,Authorization:'Bearer '+s.access_token}})}
async function token(){let s=session();if(s&&s.expires_at*1000<Date.now()+60000){const r=await fetch(databaseUrl+'/auth/v1/token?grant_type=refresh_token',{method:'POST',signal:AbortSignal.timeout(20000),headers:{apikey:key,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:s.refresh_token})});if(!r.ok){sessionStorage.removeItem('aspace-session');throw Error('Your session expired. Sign in again.')}s=await r.json();sessionStorage.setItem('aspace-session',JSON.stringify(s))}return s?.access_token}
export async function rpc(name,body={},authenticated=false){const t=authenticated?await token():undefined;if(authenticated&&!t)throw Error('Sign in to manage the website.');const r=await fetch(databaseUrl+'/rest/v1/rpc/'+name,{method:'POST',signal:AbortSignal.timeout(20000),headers:{apikey:key,'Content-Type':'application/json',...(t?{Authorization:'Bearer '+t}:{})},body:JSON.stringify(body)});const b=await r.json();if(!r.ok)throw Error(b.message||'We couldn’t connect. Please try again.');return b}
export async function uploadPhoto(file){if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5*1024*1024)throw Error('Choose JPG, PNG or WebP, up to 5 MB.');const s=session(),t=await token();if(!s||!t)throw Error('Sign in first.');const path=s.user.id+'/'+crypto.randomUUID()+'.'+({'image/jpeg':'jpg','image/png':'png','image/webp':'webp'}[file.type]);const r=await fetch(databaseUrl+'/storage/v1/object/website-products/'+path,{method:'POST',signal:AbortSignal.timeout(20000),headers:{apikey:key,Authorization:'Bearer '+t,'Content-Type':file.type},body:file});if(!r.ok)throw Error('Photo upload failed. Check your website access.');return path}
export const photoUrl=(path)=>databaseUrl+'/storage/v1/object/public/website-products/'+path.split('/').map(encodeURIComponent).join('/');
